# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.prod
    ports:
      - '9527:9527'
      # [核心修改] 新增这一行来暴露 Prisma Studio 的端口
      - '5555:5555'
    depends_on:
      - db

  db:
    image: docker.1ms.run/postgres:15
    restart: always
    environment:
      POSTGRES_USER: aleigood
      POSTGRES_PASSWORD: Hulei1234
      POSTGRES_DB: baking-saas
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: